### ISSUE TITLE
Gnome 46 Support

### ISSUE THREAD

**Issue by Aleixenandros** [hslbck/gnome-shell-extension-radio#207]
Hi!
Fedora 40 has been branched. Currently this plugin does not work in Gnome 46. I tried manually editing the metadata but wound up with additional type errors.

Thankss!!!!!

**Comment by ironbone** [comment]
The same on openSUSE Tumbleweed

**Comment by horga83** [comment]
Tried to get this working under Arch and GS 46.  Had to compile schemas but then got a "hbox.add_actor is not a function" error.
Know nothing about js and gnome so stumped at this point.

**Comment by ironbone** [comment]
In the sources everywhere, replace 
add_actor
by
add_child

**Comment by Aleixenandros** [comment]
Aquí hay una solicitud en la que funciona en gnome 46

https://github.com/hslbck/gnome-shell-extension-radio/pull/208

**Comment by hslbck** [comment]
Merged #208 to master. However still fixes from https://extensions.gnome.org/review/49525 needed to get it approved on extensions page

**Comment by InklingGirl** [comment]
Ubuntu 24.04 LTS w/ GNOME 46 has launched today.

**Comment by InklingGirl** [comment]
Still hasn't been added to the GNOME Shell Extensions page. :(

**Comment by DarthRidar** [comment]
Does not work with Fedora 40 GNOME 46.4
Can you please update? This Radio is very perfect for me.
Thanks and best regards

**Comment by DarthRidar** [comment]
> In the sources, replace everywhere (in my case 3 times) add_actor by add_child
> 
> In the metadata.json replace 45 by 46
> 
> Then install it using: sh build.sh -i
> 
> Now it works well.

runs perfectly
Edit in radioMenu.js and titleMenu.js

**Comment by CP3Urso** [comment]
Thanks to @ironbone , in terminal:

```
wget https://github.com/hslbck/gnome-shell-extension-radio/archive/refs/tags/v22.tar.gz
tar -xf v22.tar.gz --strip-components 1
sed -i 's/45/46/g' radio@hslbck.gmail.com/metadata.json
sed -i 's/add_actor/add_child/g' radio@hslbck.gmail.com/*.*
sh build.sh -i
```

**Comment by rkonikpl** [comment]
Thank you, @CP3Urso, for the suggestion. It wasn’t working for me either, and I was searching online for a solution to see what was wrong. Your suggestion solved the problem, and now I can enjoy the radio again.

**Comment by altsalt** [comment]
Hopefully [this fix](https://github.com/hslbck/gnome-shell-extension-radio/pull/211) will get a review so it can return to the extensions page and subsequent workflows.
